[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  # This rule specifically sends requests from "/api/generate-quiz"
  # directly to the "generateQuiz" function.
  from = "/api/generate-quiz"
  to = "/.netlify/functions/generateQuiz"
  status = 200

